### ISSUE TITLE
Click Area of "Click Me" button does not work on every browser "Samsung Browser"

### ISSUE THREAD

**Issue by Nixkuchengifthub** [code0-tech/pictor#49]
When clicking the button by just touching a corner it does light up as beeing clicked but nothing opens in response to the interaction, depending on how far of you are from the center of the visible button.

**Comment by Knerio** [comment]
Chrome on Android 13 is working better but the issue is on chrome also there

**Comment by nicosammito** [comment]
It could relate to the wrapper that is not working as intended:

```js

<div ref={triggerRef}>
{menuTrigger ? React.cloneElement(menuTrigger.props.children, {...buttonProps, tabIndex: 1}) : null}
</div>

```

**Comment by nicosammito** [comment]
It’s a general Issue on all browsers. Trying to move the menuTrigger props to the wrapper. Thus could potentially fix this issue

**Comment by nicosammito** [comment]
This is an issue inside of Aria. Hopefully they fix it soon:

https://github.com/adobe/react-spectrum/issues/1061

**Comment by nicosammito** [comment]
We can close this for now, because aria will not fix this any soon
