### ISSUE TITLE
Missing spacing on Menu component

### ISSUE THREAD

**Issue by Taucher2003** [code0-tech/pictor#60]
The Menu component is missing some spacing when placed on the side.

| Placement | Image |
|---|---|
| Top | ![image](https://github.com/code0-tech/pictor/assets/39954661/11310e67-f405-48ee-932e-c893b90e3ebd) |
| Bottom | ![image](https://github.com/code0-tech/pictor/assets/39954661/a3535d9a-a7d1-4df8-bcb8-f0c25f7a7265) |
| Left | ![image](https://github.com/code0-tech/pictor/assets/39954661/f0669cdb-fdcd-4941-8da0-537764ab68c2) |
| Right | ![image](https://github.com/code0-tech/pictor/assets/39954661/9d078e78-1a50-4197-bf15-3efc6d63525f) |

**Comment by nicosammito** [comment]
This is a bug inside the popover component. The menu component implements this and also this error. Thanks for reporting 👍🏻
